### ISSUE TITLE
Add date of upload for video to the YouTube linking

### ISSUE THREAD

**Issue by Zarthus** [AKPWebDesign/AKP48#3]
Currently AKP48 mentions the title, uploader, duration, views, likes and disliked. I think it'd be nice if the date of video upload would also be included in there.

```
<Zarthus> https://www.youtube.com/watch?v=iApeGGGHIfc
<AKP48> [YouTube] Evolve Alpha Potential by TheWarOwl (0:11:22 HD) | Views: 44,723 | Likes: 1,693 | Dislikes: 69
```

**Comment by AKPWebDesign** [comment]
Any particular format you'd like to see it in? I'm thinking something like:  
`[YouTube] Evolve Alpha Potential by TheWarOwl (0:11:22 HD) | Views: 44,723 | Likes: 1,693 | Dislikes: 69 | Published on Nov 3, 2014 `

Perhaps it would work better with the date before the other data:  
`[YouTube] Evolve Alpha Potential by TheWarOwl (0:11:22 HD) | Published on Nov 3, 2014 | Views: 44,723 | Likes: 1,693 | Dislikes: 69`

**Comment by Zarthus** [comment]
I'd personally put it at the end. it's probably the least important detail of them all.
